### ISSUE TITLE
ID:gyakuchikanの稼働データが総じてRatio低い

### ISSUE THREAD

**Issue by ufo801** [sakamossan/d#10]
最近追加したID:gyakuchikanの在籍嬢が他の店と比べて総じて異常にRatio低いです。でも、０でもないです。
店舗側がきちんと情報更新していないからなのか、それとも取得したデータの正規化に失敗しているのか見極めたいので、まずはデータに異常ないか調査してほしい。いや、したい。

**Comment by sakamossan** [comment]
> 店舗側がきちんと情報更新していないからなのか、

この場合だと辛いですね。
「全員ヒマしてることにしておいて、いざ呼ばれたら待たせる」というような運営されてると現状のシステムではratioが低くでてしまいます

取得しているデータの数を`COUNT(1)`などを使って取得してみると、
そもそも取得に失敗しているか、取得はできてるけどページに掲載されてる内容自体が怪しいか切り分けられそうです。

> それとも取得したデータの正規化に失敗しているのか

もし、取得できているデータの種類が少ない、あるいは特定の時間だけ取得できてないとかだとhtmlが他のページと構造が違うかもしれません。

この場合は、gyakuchikanのページのhtmlに不審な点がないかを調べることになります。
現状は https://github.com/sakamossan/d/blob/master/scrape/scraper.py#L102 この辺の処理で稼働中かどうかなどのステータスを見ています。このロジックで対応できないhtmlになっていると不正なデータとしてデータベースには入れないようになっています。

---

不明点ありましたらなんでも聞いてください。

**Comment by ufo801** [comment]
ありがとうございます。すげーわかりやすいっす。
実際店がどんな感じで回しているかはわからないので、まずはいただいた方法でしらべてみます。

**Comment by sakamossan** [comment]
パースはミスっていないことを確認した
https://github.com/sakamossan/d/commit/5ad03153d04b4bdaf532420a8d87d68b6d211cbe

そもそもお店側の問題なんじゃないかなというところ
(みんなヒマって表示にしておいて電話が来たら客を待たせるような運用をしてる?)
