### ISSUE TITLE
サーバーを立てる

### ISSUE THREAD

**Issue by sakamossan** [sakamossan/d#7]
awsかなにかでサーバを借りてきて立てる

- スクレイピングを行う基地になるのでデータ蓄積の観点からすると早い方がいい

**Comment by sakamossan** [comment]
下記の手順がよいのではないかと思っている

- packerで{AMI,vagrant-box}のイメージを作成
- vagrantで動作確認
- aws上に構築

**Comment by ufo801** [comment]
awsのアカウント開設しました。

**Comment by sakamossan** [comment]
- サーバ起動まで対応済み
- vagrant上の構築はできた: https://github.com/sakamossan/d/pull/8
- packerでのAMI作成はまだ別issueにて対応
